#ifndef PIXELSTUDIO_LOGCATEGORIES_H
#define PIXELSTUDIO_LOGCATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(lcPersistence)
Q_DECLARE_LOGGING_CATEGORY(lcExport)
Q_DECLARE_LOGGING_CATEGORY(lcIo)
Q_DECLARE_LOGGING_CATEGORY(lcTabs)

#endif // PIXELSTUDIO_LOGCATEGORIES_H
